name: Help request
description: Help request on how to use the integration
body:
  - type: markdown
    attributes:
      value: |
        Before raising a help request, make sure you have read the [documentation](https://mindrustuk.github.io/Heatmiser-for-home-assistant/).

        If your request is to do with how to do something in Home Assistant that uses this integration, you might find it better to use the Home Assistant community forum. You can also look at the dedicated [thread](https://community.home-assistant.io/t/heatmiser-neo-hub-support-ugly-and-work-in-progress) for this integration.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        A clear and concise description of what you need help with.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        Always include [diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).

        **It would really help if you could download the diagnostics data,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It will allow us to consider your request much more efficiently
  - type: textarea
    attributes:
      label: Example YAML snippet
      description: |
        If applicable, please provide an example piece of YAML that can help reproduce this problem.
        This can be from an automation, script, scene or configuration.
      render: yaml
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
